### ISSUE TITLE
Support Java 1.7

### ISSUE THREAD

**Issue by byaminov** [xebialabs-community/xldp-gradle-plugin#1]
Hi @jdewinne, could you please compile and publish this plugin using Java 1.7? Otherwise we cannot use it to generate plugins for older versions of XL Deploy.

**Comment by jdewinne** [comment]
Hi @byaminov, I think version 1.0.5 should support Java 1.7.

Regards,
Joris

**Comment by byaminov** [comment]
Yes, 1.0.5 works with Java 1.7. Thanks!
